#!/bin/bash

echo "╔═════════════════════════════════════════════════════════════╗"
echo "║                                                           ║"
echo "║              JDK 21 升级完成                             ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"

echo ""
echo "✅ 已完成："
echo "  ✓ JDK 21 安装成功"
echo "  ✓ Homebrew: openjdk@21 (21.0.10)"
echo "  ✓ 安装路径: /usr/local/opt/openjdk@21"
echo ""
echo "📋 环境变量配置："
echo "  JAVA_HOME: /usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
echo "  PATH: /usr/local/opt/openjdk@21/bin"
echo ""
echo "📝 当前 Java 版本："
export PATH="/usr/local/opt/openjdk@21/bin:$PATH"
java -version 2>&1 | head -3

echo ""
echo "🔧 永久配置："
echo "  已将以下内容添加到 ~/.zshrc"
echo "  ----------------------------------------"
echo "  export PATH=\"/usr/local/opt/openjdk@21/bin:\$PATH\""
echo "  export JAVA_HOME=\"/usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home\""
echo "  ----------------------------------------"
echo ""
echo "💡 验证 Maven 兼容性："
mvn -version 2>&1 | head -5

echo ""
echo "========================================"
echo "DevToolMP 项目状态"
echo "========================================"
echo ""

echo "✅ MySQL 容器: 运行中"
docker ps | grep devtoolmp-mysql && echo "  MySQL: localhost:3306" || echo "  MySQL: 未运行"

echo ""
echo "⚠️  后端编译错误："
echo "  后端有 4 个编译错误需要修复："
echo "   1. RatingService 类型转换问题"
echo "   2. RatingController 类型不匹配"
echo "  - 这些错误不影响 JDK 21 的安装"
echo ""
echo "========================================"
echo "下一步操作"
echo "========================================"
echo ""
echo "1. 刷新 shell 配置："
echo "   source ~/.zshrc"
echo ""
echo "2. 启动后端："
echo "   cd backend"
echo "   mvn spring-boot:run"
echo ""
echo "3. 启动前端："
echo "   cd frontend"
echo "   npm config set registry https://registry.npmjs.org/"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "========================================"
